export const TOTAL_PLAYERS = [
    {
        id: "misa_rodriguez",
        name: "Misa Rodríguez",
        date_birth: "1999-07-22",
        country: "es",
        position: "Portera",
        debut_date: "2020-10-04",
        rm_career: "2020-Actualidad",
    },
    {
        id: "yohana-gomez",
        name: "Yohana Gómez",
        date_birth: "1994-01-20",
        country: "es",
        position: "Portera",
        debut_date: "2021-01-06",
        rm_career: "2020-2021",
    },
    {
        id: "sara-ezquerro",
        name: "Sara Ezquerro",
        date_birth: "1999-04-05",
        country: "es",
        position: "Portera",
        debut_date: "2021-06-20",
        rm_career: "2020-2021",
    },
    {
        id: "meline-gerard",
        name: "Mèline Gerard",
        date_birth: "1990-05-30",
        country: "fr",
        position: "Portera",
        debut_date: "2021-10-10",
        rm_career: "2021-2023",
    },
    {
        id: "mylene-chavas",
        name: "Mylène Chavas",
        date_birth: "1998-01-07",
        country: "fr",
        position: "Portera",
        debut_date: "2023-11-04",
        rm_career: "2023-2025",
    },
    {
        id: "laia-lopez",
        name: "Laia López",
        date_birth: "2007-01-29",
        country: "es",
        position: "Portera",
        debut_date: "2025-05-11",
        rm_career: "2022-Actualidad",
    },
    {
        id: "merle_frohms",
        name: "Merle Frohms",
        date_birth: "1995-01-28",
        country: "de",
        position: "Portera",
        debut_date: "2025-08-31",
        rm_career: "2025-Actualidad",
    },
    {
        id: "ivana-andres",
        name: "Ivana Andrés",
        date_birth: "1994-07-13",
        country: "es",
        position: "Defensa central",
        debut_date: "2020-10-04",
        rm_career: "2020-2024",
    },
    {
        id: "babett-peter",
        name: "Babett Peter",
        date_birth: "1988-05-12",
        country: "de",
        position: "Defensa central",
        debut_date: "2020-10-04",
        rm_career: "2020-2022",
    },
    {
        id: "claudia-florentino",
        name: "Claudia Florentino",
        date_birth: "1998-03-10",
        country: "es",
        position: "Defensa central",
        debut_date: "2020-10-11",
        rm_career: "2020-2023",
    },
    {
        id: "daiane-limeira",
        name: "Daiane Limeira",
        date_birth: "1999-09-07",
        country: "br",
        position: "Defensa central",
        debut_date: "-",
        rm_career: "2020-2021",
    },
    {
        id: "rocio-galvez",
        name: "Rocío Gálvez",
        date_birth: "1997-04-15",
        country: "es",
        position: "Defensa central",
        debut_date: "2021-09-05",
        rm_career: "2021-Actualidad",
    },
    {
        id: "kathellen-sousa",
        name: "Kathellen Sousa",
        date_birth: "1996-04-26",
        country: "br",
        position: "Defensa central",
        debut_date: "2022-08-18",
        rm_career: "2022-2024",
    },
    {
        id: "maria-valle",
        name: "María Valle",
        date_birth: "2004-11-14",
        country: "es",
        position: "Defensa central",
        debut_date: "2024-06-14",
        rm_career: "2024, 2025-Actualidad",
    },
    {
        id: "maelle-lakrar",
        name: "Maelle Lakrar",
        date_birth: "2000-05-27",
        country: "fr",
        position: "Defensa central",
        debut_date: "2024-09-06",
        rm_career: "2024-Actualidad",
    },
    {
        id: "maria-mendez",
        name: "María Méndez",
        date_birth: "2001-04-10",
        country: "es",
        position: "Defensa central",
        debut_date: "2024-09-06",
        rm_career: "2024-Actualidad",
    },
    {
        id: "bella-andersson",
        name: "Bella Andersson",
        date_birth: "2006-07-12",
        country: "se",
        position: "Defensa central",
        debut_date: "2025-09-28",
        rm_career: "2025-Actualidad",
    },
    {
        id: "olga-carmona",
        name: "Olga Carmona",
        date_birth: "2000-06-12",
        country: "es",
        position: "Lateral izquierda",
        debut_date: "2020-10-04",
        rm_career: "2020-2025",
    },
    {
        id: "marta-corredera",
        name: "Marta Corredera",
        date_birth: "1991-10-04",
        country: "es",
        position: "Lateral izquierda",
        debut_date: "2020-10-04",
        rm_career: "2020-2023",
    },
    {
        id: "sofie-svava",
        name: "Sofie Svava",
        date_birth: "2000-08-11",
        country: "dk",
        position: "Lateral izquierda",
        debut_date: "2022-01-29",
        rm_career: "2025-Actualidad",
    },
    {
        id: "yasmim-ribeiro",
        name: "Yasmim Ribeiro",
        date_birth: "1996-10-28",
        country: "br",
        position: "Lateral izquierda",
        debut_date: "2025-01-31",
        rm_career: "2025-Actualidad",
    },
    {
        id: "sara-holmgaard",
        name: "Sara Holmgaard",
        date_birth: "1999-01-28",
        country: "dk",
        position: "Lateral izquierda",
        debut_date: "2025-08-31",
        rm_career: "2025-Actualidad",
    },
    {
        id: "kenti-robles",
        name: "Kenti Robles",
        date_birth: "1991-02-15",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2020-10-04",
        rm_career: "2020-2024",
    },
    {
        id: "samara-ortiz",
        name: "Samara Ortiz",
        date_birth: "1997-07-16",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2020-11-15",
        rm_career: "2020-2021",
    },
    {
        id: "lucia-rodriguez",
        name: "Lucía Rodríguez",
        date_birth: "1999-05-24",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2021-08-31",
        rm_career: "2021-2023",
    },
    {
        id: "oihane-hernandez",
        name: "Oihane Hernández",
        date_birth: "2000-05-04",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2023-09-15",
        rm_career: "2023-2024",
    },
    {
        id: "sheila-garcia",
        name: "Sheila García",
        date_birth: "1997-03-15",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2024-09-06",
        rm_career: "2024-Actualidad",
    },
    {
        id: "antonia-silva",
        name: "Antonia Silva",
        date_birth: "1994-04-26",
        country: "br",
        position: "Lateral derecha",
        debut_date: "2024-10-17",
        rm_career: "2024-Actualidad",
    },
    {
        id: "silvia-cristobal",
        name: "Silvia Cristóbal",
        date_birth: "2008-05-01",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2025-05-12",
        rm_career: "2021-Actualidad",
    },
    {
        id: "noe-bejarano",
        name: "Noe Bejarano",
        date_birth: "2006-06-27",
        rm_career: "2020-2024",
    },
    {
        id: "babett-peter",
        name: "Babett Peter",
        date_birth: "1988-05-12",
        country: "de",
        position: "Defensa central",
        debut_date: "2020-10-04",
        rm_career: "2020-2022",
    },
    {
        id: "claudia-florentino",
        name: "Claudia Florentino",
        date_birth: "1998-03-10",
        country: "es",
        position: "Defensa central",
        debut_date: "2020-10-11",
        rm_career: "2020-2023",
    },
    {
        id: "daiane-limeira",
        name: "Daiane Limeira",
        date_birth: "1999-09-07",
        country: "br",
        position: "Defensa central",
        debut_date: "-",
        rm_career: "2020-2021",
    },
    {
        id: "rocio-galvez",
        name: "Rocío Gálvez",
        date_birth: "1997-04-15",
        country: "es",
        position: "Defensa central",
        debut_date: "2021-09-05",
        rm_career: "2021-Actualidad",
    },
    {
        id: "kathellen-sousa",
        name: "Kathellen Sousa",
        date_birth: "1996-04-26",
        country: "br",
        position: "Defensa central",
        debut_date: "2022-08-18",
        rm_career: "2022-2024",
    },
    {
        id: "maria-valle",
        name: "María Valle",
        date_birth: "2004-11-14",
        country: "es",
        position: "Defensa central",
        debut_date: "2024-06-14",
        rm_career: "2024, 2025-Actualidad",
    },
    {
        id: "maelle-lakrar",
        name: "Maelle Lakrar",
        date_birth: "2000-05-27",
        country: "fr",
        position: "Defensa central",
        debut_date: "2024-09-06",
        rm_career: "2024-Actualidad",
    },
    {
        id: "maria-mendez",
        name: "María Méndez",
        date_birth: "2001-04-10",
        country: "es",
        position: "Defensa central",
        debut_date: "2024-09-06",
        rm_career: "2024-Actualidad",
    },
    {
        id: "bella-andersson",
        name: "Bella Andersson",
        date_birth: "2006-07-12",
        country: "se",
        position: "Defensa central",
        debut_date: "2025-09-28",
        rm_career: "2025-Actualidad",
    },
    {
        id: "olga-carmona",
        name: "Olga Carmona",
        date_birth: "2000-06-12",
        country: "es",
        position: "Lateral izquierda",
        debut_date: "2020-10-04",
        rm_career: "2020-2025",
    },
    {
        id: "marta-corredera",
        name: "Marta Corredera",
        date_birth: "1991-10-04",
        country: "es",
        position: "Lateral izquierda",
        debut_date: "2020-10-04",
        rm_career: "2020-2023",
    },
    {
        id: "sofie-svava",
        name: "Sofie Svava",
        date_birth: "2000-08-11",
        country: "dk",
        position: "Lateral izquierda",
        debut_date: "2022-01-29",
        rm_career: "2025-Actualidad",
    },
    {
        id: "yasmim-ribeiro",
        name: "Yasmim Ribeiro",
        date_birth: "1996-10-28",
        country: "br",
        position: "Lateral izquierda",
        debut_date: "2025-01-31",
        rm_career: "2025-Actualidad",
    },
    {
        id: "sara-holmgaard",
        name: "Sara Holmgaard",
        date_birth: "1999-01-28",
        country: "dk",
        position: "Lateral izquierda",
        debut_date: "2025-08-31",
        rm_career: "2025-Actualidad",
    },
    {
        id: "kenti-robles",
        name: "Kenti Robles",
        date_birth: "1991-02-15",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2020-10-04",
        rm_career: "2020-2024",
    },
    {
        id: "samara-ortiz",
        name: "Samara Ortiz",
        date_birth: "1997-07-16",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2020-11-15",
        rm_career: "2020-2021",
    },
    {
        id: "lucia-rodriguez",
        name: "Lucía Rodríguez",
        date_birth: "1999-05-24",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2021-08-31",
        rm_career: "2021-2023",
    },
    {
        id: "oihane-hernandez",
        name: "Oihane Hernández",
        date_birth: "2000-05-04",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2023-09-15",
        rm_career: "2023-2024",
    },
    {
        id: "sheila-garcia",
        name: "Sheila García",
        date_birth: "1997-03-15",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2024-09-06",
        rm_career: "2024-Actualidad",
    },
    {
        id: "antonia-silva",
        name: "Antonia Silva",
        date_birth: "1994-04-26",
        country: "br",
        position: "Lateral derecha",
        debut_date: "2024-10-17",
        rm_career: "2024-Actualidad",
    },
    {
        id: "silvia-cristobal",
        name: "Silvia Cristóbal",
        date_birth: "2008-05-01",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2025-05-12",
        rm_career: "2021-Actualidad",
    },
    {
        id: "noe-bejarano",
        name: "Noe Bejarano",
        date_birth: "2006-06-27",
        country: "es",
        position: "Lateral derecha",
        debut_date: "2025-05-18",
        rm_career: "2023-Actualidad",
    },
    {
        id: "teresa-abelleira",
        name: "Teresa Abelleira",
        date_birth: "2000-01-09",
        country: "es",
        position: "Centrocampista",
        debut_date: "2020-10-04",
        rm_career: "2020-Actualidad",
    },
    {
        id: "kosovare-asllani",
        name: "Kosovare Asllani",
        date_birth: "1989-07-29",
        country: "se",
        position: "Centrocampista",
        debut_date: "2020-10-04",
        rm_career: "2020-2022",
    },
    {
        id: "maite-oroz",
        name: "Maite Oroz",
        date_birth: "1998-03-25",
        country: "es",
        position: "Centrocampista",
        debut_date: "2020-10-04",
        rm_career: "2020-2024",
    },
    {
        id: "aurelie-kaci",
        name: "Aurelie Kaci",
        date_birth: "1989-12-19",
        country: "fr",
        position: "Centrocampista",
        debut_date: "2020-10-04",
        rm_career: "2020-2022",
    },

    {
        id: "thaisa-moreno",
        name: "Thaisa Moreno",
        date_birth: "1988-12-17",
        country: "br",
        position: "Centrocampista",
        debut_date: "2020-11-04",
        rm_career: "2020-2021",
    },
    {
        id: "malena-ortiz",
        name: "Malena Ortiz",
        date_birth: "1997-07-16",
        country: "es",
        position: "Centrocampista",
        debut_date: "2020-12-13",
        rm_career: "2020-2021",
    },
    {
        id: "claudia-zornoza",
        name: "Claudia Zornoza",
        date_birth: "1990-10-20",
        country: "es",
        position: "Centrocampista",
        debut_date: "2021-08-31",
        rm_career: "2021-2024",
    },
    {
        id: "freja-siri",
        name: "Freja Siri",
        date_birth: "1998-05-24",
        country: "se",
        position: "Centrocampista",
        debut_date: "2022-09-21",
        rm_career: "2022-2024",
    },
    {
        id: "sandie-toletti",
        name: "Sandie Toletti",
        date_birth: "1995-07-13",
        country: "fr",
        position: "Centrocampista",
        debut_date: "2022-08-18",
        rm_career: "2022-Actualidad",
    },
    {
        id: "caroline-weir",
        name: "Caroline Weir",
        date_birth: "1995-06-20",
        country: "gb-sct",
        position: "Centrocampista",
        debut_date: "2022-08-18",
        rm_career: "2022-Actualidad",
    },
    {
        id: "olaya-rodriguez",
        name: "Olaya Rodríguez",
        date_birth: "2005-05-10",
        country: "es",
        position: "Centrocampista",
        debut_date: "2023-11-10",
        rm_career: "2022-2024",
    },
    {
        id: "filippa-angeldahl",
        name: "Filippa Angeldahl",
        date_birth: "1997-07-14",
        country: "se",
        position: "Centrocampista",
        debut_date: "2024-09-06",
        rm_career: "2024-Actualidad",
    },
    {
        id: "melanie-leupolz",
        name: "Melanie Leupolz",
        date_birth: "1994-04-14",
        country: "de",
        position: "Centrocampista",
        debut_date: "2024-09-06",
        rm_career: "2024-2025",
    },
    {
        id: "irune-dorado",
        name: "Irune Dorado",
        date_birth: "2008-03-22",
        country: "es",
        position: "Centrocampista",
        debut_date: "2025-01-31",
        rm_career: "2021-Actualidad",
    },
    {
        id: "elsa-santos",
        name: "Elsa Santos",
        date_birth: "2025-03-09",
        country: "es",
        position: "Centrocampista",
        debut_date: "2007-05-12",
        rm_career: "2022-2025",
    },
    {
        id: "hanna-bennison",
        name: "Hanna Bennison",
        date_birth: "2002-10-16",
        country: "se",
        position: "Centrocampista",
        debut_date: "2025-09-05",
        rm_career: "2025-Actualidad",
    },
    {
        id: "sara-dabritz",
        name: "Sara Däbritz",
        date_birth: "1995-02-15",
        country: "de",
        position: "Centrocampista",
        debut_date: "2025-09-05",
        rm_career: "2025-Actualidad",
    },
    {
        id: "adriana-folgado",
        name: "Adriana Folgado",
        date_birth: "2007-04-01",
        country: "es",
        position: "Centrocampista",
        debut_date: "2025-09-21",
        rm_career: "2020-Actualidad",
    },
    {
        id: "sofia-jakobsson",
        name: "Sofia Jakobsson",
        date_birth: "1990-04-23",
        country: "se",
        position: "Extremo izquierdo",
        debut_date: "2020-10-04",
        rm_career: "2020-2021",
    },
    {
        id: "athenea-del-castillo",
        name: "Athenea del Castillo",
        date_birth: "2000-10-24",
        country: "es",
        position: "Extremo izquierdo",
        debut_date: "2021-08-31",
        rm_career: "2021-Actualidad",
    },
    {
        id: "linda-caicedo",
        name: "Linda Caicedo",
        date_birth: "2005-02-22",
        country: "co",
        position: "Extremo izquierdo",
        debut_date: "2023-03-04",
        rm_career: "2023-Actualidad",
    },
    {
        id: "paula-comendador",
        name: "Paula Comendador",
        date_birth: "2007-01-12",
        country: "es",
        position: "Extremo izquierdo",
        debut_date: "2023-11-26",
        rm_career: "2023-Actualidad",
    },
    {
        id: "marta-cardona",
        name: "Marta Cardona",
        date_birth: "1995-05-26",
        country: "es",
        position: "Extremo derecho",
        debut_date: "2020-10-04",
        rm_career: "2020-2022",
    },
    {
        id: "chi-obogagu",
        name: "Chi Obogagu",
        date_birth: "1992-09-10",
        country: "gb-eng",
        position: "Extremo derecho",
        debut_date: "2020-10-11",
        rm_career: "2020-2021",
    },
    {
        id: "paula-partido",
        name: "Paula Partido",
        date_birth: "2005-03-02",
        country: "es",
        position: "Extremo derecho",
        debut_date: "2021-12-22",
        rm_career: "2020-2023",
    },
    {
        id: "sara-martin",
        name: "Sara Martin",
        date_birth: "2004-10-06",
        country: "es",
        position: "Extremo derecho",
        debut_date: "2022-03-01",
        rm_career: "2020-Actualidad",
    },
    {
        id: "naomie-feller",
        name: "Naomie Feller",
        date_birth: "2001-11-06",
        country: "fr",
        position: "Extremo derecho",
        debut_date: "2022-08-18",
        rm_career: "2022-Actualidad",
    },
    {
        id: "hayley-raso",
        name: "Hayley Raso",
        date_birth: "1994-09-05",
        country: "au",
        position: "Extremo derecho",
        debut_date: "1994-09-05",
        rm_career: "2023-2024",
    },
    {
        id: "eva-navarro",
        name: "Eva Navarro",
        date_birth: "2001-01-27",
        country: "es",
        position: "Extremo derecho",
        debut_date: "2024-09-06",
        rm_career: "2024-Actualidad",
    },
    {
        id: "lotte-keukelaar",
        name: "Lotte Keukelaar",
        date_birth: "2005-09-25",
        country: "nl",
        position: "Extremo derecho",
        debut_date: "2025-10-04",
        rm_career: "2025-Actualidad",
    },
    {
        id: "lorena-navarro",
        name: "Lorena Navarro",
        date_birth: "2000-11-11",
        country: "es",
        position: "Delantera",
        debut_date: "2020-10-04",
        rm_career: "2020-2023",
    },
    {
        id: "jessica-martinez",
        name: "Jessica Martínez",
        date_birth: "1999-06-14",
        country: "pry",
        position: "Delantera",
        debut_date: "2020-10-18",
        rm_career: "2020-2021",
    },
    {
        id: "ariana-arias",
        name: "Ariana Arias",
        date_birth: "2003-05-23",
        country: "es",
        position: "Delantera",
        debut_date: "2020-11-04",
        rm_career: "2020-2022",
    },
    {
        id: "esther-gonzalez",
        name: "Esther González",
        date_birth: "1992-12-08",
        country: "es",
        position: "Delantera",
        debut_date: "2021-08-31",
        rm_career: "2021-2023",
    },
    {
        id: "nahikari-garcia",
        name: "Nahikari García",
        date_birth: "1997-03-10",
        country: "es",
        position: "Delantera",
        debut_date: "2021-08-31",
        rm_career: "2021-2023",
    },
    {
        id: "caroline-moller",
        name: "Caroline Møller",
        date_birth: "1998-12-19",
        country: "dk",
        position: "Delantera",
        debut_date: "2021-08-31",
        rm_career: "2021-2025",
    },
    {
        id: "carla-camacho",
        name: "Carla Camacho",
        date_birth: "2005-05-02",
        country: "es",
        position: "Delantera",
        debut_date: "2021-10-10",
        rm_career: "2020-2025",
    },
    {
        id: "bea-ortiz",
        name: "Bea Ortiz",
        date_birth: "2004-03-27",
        country: "es",
        position: "Delantera",
        debut_date: "2023-05-19",
        rm_career: "2022-Actualidad",
    },
    {
        id: "signe-bruun",
        name: "Signe Bruun",
        date_birth: "1998-04-06",
        country: "dk",
        position: "Delantera",
        debut_date: "2023-09-15",
        rm_career: "2023-Actualidad",
    },
    {
        id: "marisa-garcia",
        name: "Marisa García",
        date_birth: "2006-06-22",
        country: "es",
        position: "Delantera",
        debut_date: "2023-11-23",
        rm_career: "2021-2025",
    },
    {
        id: "alba-redondo",
        name: "Alba Redondo",
        date_birth: "1996-08-27",
        country: "es",
        position: "Delantera",
        debut_date: "2024-09-06",
        rm_career: "2024-Actualidad",
    },
    {
        id: "iris-ashley-santiago",
        name: "Iris Ashley Santiago",
        date_birth: "2007-11-09",
        country: "es",
        position: "Delantera",
        debut_date: "2025-09-21",
        rm_career: "2022-Actualidad",
    },
]