export const TEAMS = [
    {
        id: "fc-barcelona",
        name: "FC Barcelona",
        city: "Barcelona",
        country: "es",
    },
    {
        id: "valencia-cf",
        name: "Valencia CF",
        city: "Valencia",
        country: "es",
    },
    {
        id: "rayo-vallecano",
        name: "Rayo Vallecano",
        city: "Madrid",
        country: "es",
    },
    {
        id: "deportivo-abanca",
        name: "Deportivo Abanca",
        city: "La Coruña",
        country: "es",
    },
    {
        id: "sd-eibar",
        name: "SD Eibar",
        city: "Eibar",
        country: "es",
    },
    {
        id: "costa-adeje-tenerife",
        name: "Costa Adeje Tenerife",
        city: "Tenerife",
        country: "es",
    },
    {
        id: "athletic-club",
        name: "Athletic Club",
        city: "Bilbao",
        country: "es",
    },
    {
        id: "real-betis",
        name: "Real Betis",
        city: "Sevilla",
        country: "es",
    },
    {
        id: "sevilla-fc",
        name: "Sevilla FC",
        city: "Sevilla",
        country: "es",
    },
    {
        id: "levante-ud",
        name: "Levante UD",
        city: "Valencia",
        country: "es",
    },
    {
        id: "espanyol",
        name: "Espanyol",
        city: "Barcelona",
        country: "es",
    },
    {
        id: "atletico-de-madrid",
        name: "Atletico de Madrid",
        city: "Madrid",
        country: "es",
    },
    {
        id: "sporting-de-huelva",
        name: "Sporting de Huelva",
        city: "Huelva",
        country: "es",
    },
    {
        id: "madrid-cff",
        name: "Madrid CFF",
        city: "Madrid",
        country: "es",
    },
    {
        id: "santa-teresa",
        name: "Santa Teresa",
        city: "Badajoz",
        country: "es",
    },
    {
        id: "real-sociedad",
        name: "Real Sociedad",
        city: "San Sebastian",
        country: "es",
    },
    {
        id: "dux-logrono",
        name: "DUX-Logroño",
        city: "Logroño",
        country: "es",
    },
    {
        id: "sparta-de-praga",
        name: "Sparta de Praga",
        city: "Praga",
        country: "cze",
    },
    {
        id: "wacker-innsbruck",
        name: "Wacker Innsbruck",
        city: "Innsbruck",
        country: "aut",
    },
    {
        id: "ffc-turbine-potsdam",
        name: "FFC Turbine Potsdam",
        city: "Potsdam",
        country: "de",
    },
    {
        id: "cacereno",
        name: "Cacereño",
        city: "Cáceres",
        country: "es",
    },
    {
        id: "fundacion-albacete",
        name: "Fundación Albacete",
        city: "Albacete",
        country: "es",
    },
    {
        id: "manchester-city",
        name: "Manchester City",
        city: "Manchester",
        country: "gb-eng",
    },
    {
        id: "kharkiv",
        name: "Kharkiv",
        city: "Kharkiv",
        country: "ukr",
    },
    {
        id: "breidablik",
        name: "Breidablik",
        city: "Kópavogur",
        country: "isl",
    },
    {
        id: "psg",
        name: "PSG",
        city: "París",
        country: "fr",
    },
    {
        id: "alaves",
        name: "Alavés",
        city: "Vitoria",
        country: "es",
    },
    {
        id: "villarreal-cf",
        name: "Villarreal CF",
        city: "Villarreal",
        country: "es",
    },
    {
        id: "alhama",
        name: "Alhama",
        city: "Alhama de Murcia",
        country: "es",
    },
    {
        id: "levante-badalona",
        name: "Levante Badalona",
        city: "Badalona",
        country: "es",
    },
    {
        id: "fundacion-osasuna",
        name: "Fundación Osasuna",
        city: "Pamplona",
        country: "es",
    },
    {
        id: "slavia-de-praga",
        name: "Slavia de Praga",
        city: "Praga",
        country: "cze",
    },
    {
        id: "sturm-graz",
        name: "Sturm Graz",
        city: "Graz",
        country: "aut",
    },
    {
        id: "rosenborg",
        name: "Rosenborg",
        city: "Trondheim",
        country: "nor",
    },
    {
        id: "vllaznia",
        name: "Vllaznia",
        city: "Shkodër",
        country: "alb"
    },
    {
        id: "chelsea",
        name: "Chelsea",
        city: "Londres",
        country: "gb-eng"
    },
    {
        id: "tigres-uanl",
        name: "Tigres UANL",
        city: "Monterrey",
        country: "mx"
    },
    {
        id: "america",
        name: "América",
        city: "Ciudad de México",
        country: "mx",
    },
    {
        id: "valerenga",
        name: "Valerenga",
        city: "Oslo",
        country: "nor",
    },
    {
        id: "granada-cf",
        name: "Granada CF",
        city: "Granada",
        country: "es",
    },
    {
        id: "hacken",
        name: "Häcken",
        city: "Gotemburgo",
        country: "se",
    },
    {
        id: "paris-fc",
        name: "Paris FC",
        city: "París",
        country: "fr",
    },
    {
        id: "sporting-de-portugal",
        name: "Sporting de Portugal",
        city: "Portugal",
        country: "prt",
    },
    {
        id: "celtic-fc",
        name: "Celtic FC",
        city: "Glasgow",
        country: "gb-sct",
    },
    {
        id: "twente",
        name: "Twente",
        city: "Enschede",
        country: "nl",
    },
    {
        id: "arsenal",
        name: "Arsenal",
        city: "Londres",
        country: "gb-eng",
    },
    {
        id: "fc-union-berlin",
        name: "FC Union Berlin",
        city: "Berlín",
        country: "de",
    },
    {
        id: "bayern-munich",
        name: "Bayern de Múnich",
        city: "Múnich",
        country: "de",
    },
    {
        id: "eintracht-de-frankfurt",
        name: "Eintracht de Frankfurt",
        city: "Frankfurt",
        country: "de",
    },
    {
        id: "as-roma",
        name: "AS Roma",
        city: "Roma",
        country: "ita",
    },

]