export const CALENDAR = [
    {
        id: "real-madrid-vs-sevilla",
        team1: "Real Madrid",
        team2: "Sevilla FC",
        homeaway: "home",
        date: "2026-01-10",
        time: "17:00 CEST",
        competition: "Liga F",
        matchday: "Jornada 15",
        stadium: 'Estadio Alfredo Di Stefano',
        tv: 'DAZN',
    },
    {
        id: "real-madrid-vs-athletic",
        team1: "Real Madrid",
        team2: "Athletic Club",
        homeaway: "home",
        date: "2026-01-13",
        time: "17:00 CEST",
        competition: "Liga F",
        matchday: "Jornada 17",
        stadium: 'Estadio Alfredo Di Stefano',
        tv: 'DAZN',
    },
    {
        id: "levante-vs-real-madrid",
        team1: "Levante UD",
        team2: "Real Madrid",
        homeaway: "away",
        date: "2026-01-17",
        time: "17:00 CEST",
        competition: "Liga F",
        matchday: "Jornada 16",
        stadium: 'Ciudad Deportiva de Buñol',
        tv: 'DAZN',
    },
    {
        id: "real-madrid-vs-atletico-de-madrid",
        team1: "Real Madrid",
        team2: "Atlético de Madrid",
        homeaway: "neutral",
        date: "2026-01-20",
        time: "19:00 CEST",
        matchday: "Semifinal",
        competition: "Supercopa de España",
        stadium: 'Estadio SkyFi Castalia',
        tv: 'Teledeporte',
    },
    {
        id: "deportivo-vs-real-madrid",
        team1: "Deportivo de La Coruña",
        team2: "Real Madrid",
        homeaway: "away",
        date: "2026-02-01",
        time: "",
        matchday: "Jornada 18",
        competition: "Liga F",
        stadium: 'Estadio de Riazor',
        tv: 'DAZN',
    },
    {
        id: "real-madrid-vs-espanyol",
        team1: "Real Madrid",
        team2: "Espanyol",
        homeaway: "home",
        date: "2026-02-08",
        time: "",
        matchday: "Jornada 19",
        competition: "Liga F",
        stadium: 'Estadio Alfredo Di Stefano',
        tv: 'DAZN',
    },
    {
        id: "paris-fc-vs-real-madrid",
        team1: "Paris FC",
        team2: "Real Madrid",
        homeaway: "away",
        date: "2026-02-11",
        time: "21:00 CEST",
        matchday: "Playoffs - Ida",
        competition: "UWCL",
        stadium: 'Stade Charléty',
        tv: 'Disney +',
    },
    {
        id: "alhama-vs-real-madrid",
        team1: "Alhama El Pozo",
        team2: "Real Madrid",
        homeaway: "away",
        date: "2026-02-15",
        time: "",
        matchday: "Jornada 20",
        competition: "Liga F",
        stadium: 'Campo Municipal de Fútbol José Kubala',
        tv: 'DAZN',
    },
    {
        id: "real-madrid-vs-paris-fc",
        team1: "Real Madrid",
        team2: "Paris FC",
        homeaway: "home",
        date: "2026-02-18",
        time: "18:45 CEST",
        matchday: "Playoffs - Vuelta",
        competition: "UWCL",
        stadium: 'Estadio Alfredo Di Stefano',
        tv: 'Disney +',
    },
    {
        id: "real-madrid-vs-tenerife",
        team1: "Real Madrid",
        team2: "Tenerife",
        homeaway: "home",
        date: "2026-02-22",
        time: "",
        matchday: "Jornada 21",
        competition: "Liga F",
        stadium: 'Estadio Alfredo Di Stefano',
        tv: 'DAZN',
    },
    {
        id: "real-sociedad-vs-real-madrid",
        team1: "Real Sociedad",
        team2: "Real Madrid",
        homeaway: "away",
        date: "2026-03-15",
        time: "",
        matchday: "Jornada 22",
        competition: "Liga F",
        stadium: 'Campo José Luis Orbegozo',
        tv: 'DAZN',
    },
    {
        id: "sd-eibar-vs-real-madrid",
        team1: "SD Eibar",
        team2: "Real Madrid",
        homeaway: "away",
        date: "2026-03-22",
        time: "",
        matchday: "Jornada 23",
        competition: "Liga F",
        stadium: 'Estadio Municipal de Ipurúa',
        tv: 'DAZN',
    },
    {
        id: "real-madrid-vs-fc-barcelona",
        team1: "Real Madrid",
        team2: "FC Barcelona",
        homeaway: "home",
        date: "2026-03-29",
        time: "",
        matchday: "Jornada 24",
        competition: "Liga F",
        stadium: 'Estadio Alfredo Di Stefano',
        tv: 'DAZN',
    },
    {
        id: "madrid-cff-vs-real-madrid",
        team1: "Madrid CFF",
        team2: "Real Madrid",
        homeaway: "away",
        date: "2026-04-05",
        time: "",
        matchday: "Jornada 25",
        competition: "Liga F",
        stadium: 'Estadio Fernando Torres',
        tv: 'DAZN',
    },
    {
        id: "real-madrid-vs-dux-logroño",
        team1: "Real Madrid",
        team2: "DUX Logroño",
        homeaway: "home",
        date: "2026-04-26",
        time: "",
        matchday: "Jornada 26",
        competition: "Liga F",
        stadium: 'Estadio Alfredo Di Stefano',
        tv: 'DAZN',
    },
    {
        id: "sevilla-fc-vs-real-madrid",
        team1: "Sevilla FC",
        team2: "Real Madrid",
        homeaway: "away",
        date: "2026-05-03",
        time: "",
        matchday: "Jornada 27",
        competition: "Liga F",
        stadium: 'Estadio Jesús Navas',
        tv: 'DAZN',
    },
    {
        id: "real-madrid-vs-atletico-de-madrid",
        team1: "Real Madrid",
        team2: "Atlético de Madrid",
        homeaway: "home",
        date: "2026-05-10",
        time: "",
        matchday: "Jornada 28",
        competition: "Liga F",
        stadium: 'Estadio Alfredo Di Stefano',
        tv: 'DAZN',
    },
    {
        id: "levante-badalona-vs-real-madrid",
        team1: "Levante Badalona",
        team2: "Real Madrid",
        homeaway: "away",
        date: "2026-05-24",
        time: "",
        matchday: "Jornada 29",
        competition: "Liga F",
        stadium: 'Estadi Municipal de Badalona',
        tv: 'DAZN',
    },
    {
        id: "real-madrid-vs-granada-cf",
        team1: "Real Madrid",
        team2: "Granada CF",
        homeaway: "home",
        date: "2026-05-31",
        time: "",
        matchday: "Jornada 30",
        competition: "Liga F",
        stadium: 'Estadio Alfredo Di Stefano',
        tv: 'DAZN',
    },
];
