export const COUNTRIES = {
    'es': { name: 'España' },
    'esp': { name: 'España' },
    'de': { name: 'Alemania' },
    'ger': { name: 'Alemania' },
    'fr': { name: 'Francia' },
    'fra': { name: 'Francia' },
    'gb-sct': { name: 'Escocia' },
    'sco': { name: 'Escocia' },
    'br': { name: 'Brasil' },
    'bra': { name: 'Brasil' },
    'co': { name: 'Colombia' },
    'col': { name: 'Colombia' },
    'dk': { name: 'Dinamarca' },
    'den': { name: 'Dinamarca' },
    'se': { name: 'Suecia' },
    'swe': { name: 'Suecia' },
    'nl': { name: 'Países Bajos' },
    'ned': { name: 'Países Bajos' },
    'gb-eng': { name: 'Inglaterra' },
    'eng': { name: 'Inglaterra' },
    'aut': { name: 'Austria' },
    'ukr': { name: 'Ucrania' },
    'cze': { name: 'República Checa' },
    'isl': { name: 'Islandia' },
    'nor': { name: 'Noruega' },
    'alb': { name: 'Albania' },
    'mx': { name: 'México' },
    'mex': { name: 'México' },
    'prt': { name: 'Portugal' },
    'por': { name: 'Portugal' },
    'ita': { name: 'Italia' },
    'au': { name: 'Australia' },
    'aus': { name: 'Australia' },
    'pry': { name: 'Paraguay' },
    'par': { name: 'Paraguay' },

}

