export const SQUAD = [
    {
        id: "misa_rodriguez",
        name: "Misa Rodríguez",
        id_jugadora: 1,
        position: "Portera",
        date_birth: "1999-07-22",
        birth_place: "Las Palmas de Gran Canaria, España",
        country: "es",
        height: 1.73,
        weight: 66,
        number: 1,
    },
    {
        id: "merle_frohms",
        name: "Merle Frohms",
        id_jugadora: 76,
        position: "Portera",
        date_birth: "1995-01-28",
        birth_place: "Celle, Alemania",
        country: "de",
        height: 1.75,
        weight: 60,
        number: 13,
    },
    {
        id: "antonia_silva",
        name: "Antonia Silva",
        id_jugadora: 62,
        position: "Defensa lateral derecha",
        date_birth: "1994-04-26",
        birth_place: "Riacho de Santana, Brasil",
        country: "br",
        height: 1.70,
        weight: 64,
        number: 2,
    },
    {
        id: "rocio_galvez",
        name: "Rocio Gálvez",
        id_jugadora: 30,
        position: "Defensa central",
        date_birth: "1997-04-15",
        birth_place: "Córdoba, España",
        country: "es",
        height: 1.74,
        weight: 68,
        number: 4,
    },
    {
        id: "yasmim_ribeiro",
        name: "Yasmim Ribeiro",
        id_jugadora: 64,
        position: "Defensa lateral izquierda",
        date_birth: "1996-10-28",
        birth_place: "Governador Valadares, Brasil",
        country: "br",
        height: 1.63,
        weight: 57,
        number: 12,
    },
    {
        id: "maria_mendez",
        name: "María Méndez",
        id_jugadora: 65,
        position: "Defensa central",
        date_birth: "2001-04-10",
        birth_place: "Oviedo, España",
        country: "es",
        height: 1.73,
        weight: 65,
        number: 14,
    },
    {
        id: "sheila_garcia",
        name: "Sheila García",
        id_jugadora: 66,
        position: "Defensa lateral derecha",
        date_birth: "1997-03-15",
        birth_place: "Yunquera de Henares, España",
        country: "es",
        height: 1.64,
        weight: 51,
        number: 15,
    },
    {
        id: "sara_holmgaard",
        name: "Sara Holmgaard",
        id_jugadora: 78,
        position: "Defensa lateral izquierda",
        date_birth: "1999-01-28",
        birth_place: "Bording, Dinamarca",
        country: "dk",
        height: 1.74,
        weight: 62,
        number: 21,
    },
    {
        id: "bella_andersson",
        name: "Bella Andersson",
        id_jugadora: 79,
        position: "Defensa central",
        date_birth: "2006-07-12",
        birth_place: "Estocolmo, Suecia",
        country: "se",
        height: 1.83,
        weight: 70,
        number: 22,
    },
    {
        id: "maelle_lakrar",
        name: "Maëlle Lakrar",
        id_jugadora: 69,
        position: "Defensa central",
        date_birth: "2000-05-27",
        birth_place: "Orange, Francia",
        country: "fr",
        height: 1.72,
        weight: 61.5,
        number: 23,
    },
    {
        id: "teresa_abelleira",
        name: "Teresa Abelleira",
        id_jugadora: 16,
        position: "Centrocampista",
        date_birth: "2000-01-09",
        birth_place: "Pontevedra, España",
        country: "es",
        height: 1.60,
        weight: 59,
        number: 3,
    },
    {
        id: "sandie_toletti",
        name: "Sandie Toletti",
        id_jugadora: 43,
        position: "Centrocampista",
        date_birth: "1995-07-13",
        birth_place: "Bagnols-sur-Céze, Francia",
        country: "fr",
        height: 1.69,
        weight: 61,
        number: 6,
    },
    {
        id: "sara_dabritz",
        name: "Sara Däbritz",
        id_jugadora: 75,
        position: "Centrocampista",
        date_birth: "1995-02-15",
        birth_place: "Amberg, Alemania",
        country: "de",
        height: 1.71,
        weight: 65,
        number: 8,
    },
    {
        id: "caroline_weir",
        name: "Caroline Weir",
        id_jugadora: 44,
        position: "Centrocampista",
        date_birth: "1995-06-20",
        birth_place: "Dunfermline, Escocia",
        country: "gb-sct",
        height: 1.73,
        weight: 62,
        number: 10,
    },
    {
        id: "filippa_angeldahl",
        name: "Filippa Angeldahl",
        id_jugadora: 68,
        position: "Centrocampista",
        date_birth: "1997-07-14",
        birth_place: "Uppsala, Suecia",
        country: "se",
        height: 1.70,
        weight: 60,
        number: 16,
    },
    {
        id: "hanna_bennison",
        name: "Hanna Bennison",
        id_jugadora: 77,
        position: "Centrocampista",
        date_birth: "2002-10-16",
        birth_place: "Lomma, Suecia",
        country: "se",
        height: 1.65,
        weight: 60,
        number: 17,
    },
    {
        id: "paula_comendador",
        name: "Paula Comendador",
        id_jugadora: 56,
        position: "Extremo izquierdo",
        date_birth: "2007-01-12",
        birth_place: "Madrid, España",
        country: "es",
        height: 1.66,
        weight: 52,
        number: 5,
    },
    {
        id: "athenea_del_castillo",
        name: "Athenea del Castillo",
        id_jugadora: 32,
        position: "Extremo derecho",
        date_birth: "2000-10-24",
        birth_place: "Solares, España",
        country: "es",
        height: 1.60,
        weight: 52,
        number: 22,
    },
    {
        id: "signe_bruun",
        name: "Signe Bruun",
        id_jugadora: 50,
        position: "Delantera centro",
        date_birth: "1998-04-06",
        birth_place: "Randers, Dinamarca",
        country: "dk",
        height: 1.78,
        weight: 68,
        number: 9,
    },
    {
        id: "alba_redondo",
        name: "Alba Redondo",
        id_jugadora: 63,
        position: "Delantera centro",
        date_birth: "1996-08-27",
        birth_place: "Albacete, España",
        country: "es",
        height: 1.69,
        weight: 61,
        number: 11,
    },
    {
        id: "linda_caicedo",
        name: "Linda Caicedo",
        id_jugadora: 46,
        position: "Extremo izquierdo",
        date_birth: "2005-02-22",
        birth_place: "Cali, Colombia",
        country: "co",
        height: 1.63,
        weight: 54,
        number: 18,
    },
    {
        id: "eva_navarro",
        name: "Eva Navarro",
        id_jugadora: 67,
        position: "Extremo derecho",
        date_birth: "2001-01-27",
        birth_place: "Yecla, España",
        country: "es",
        height: 1.60,
        weight: 54,
        number: 19,
    },
    {
        id: "naomie_feller",
        name: "Naomie Feller",
        id_jugadora: 47,
        position: "Delantera centro",
        date_birth: "2001-11-06",
        birth_place: "París, Francia",
        country: "fr",
        height: 1.70,
        weight: 65,
        number: 20,
    },
    {
        id: "lotte_keukelaar",
        name: "Lotte Keukelaar",
        id_jugadora: 82,
        position: "Extremo izquierdo",
        date_birth: "2005-09-25",
        birth_place: "Hilversum, Países Bajos",
        country: "nl",
        height: 1.71,
        weight: 62,
        number: 24,
    },
    { id: "irune_dorado", name: "Irune Dorado", position: "Canterana", date_birth: "", birth_place: "", country: "es", height: 0, weight: 0, number: 28 },
    { id: "silvia_cristobal", name: "Silvia Cristóbal", position: "Canterana", date_birth: "", birth_place: "", country: "es", height: 0, weight: 0, number: 29 },
    { id: "iris_ashley_santiago", name: "Iris Ashley", position: "Canterana", date_birth: "", birth_place: "", country: "es", height: 0, weight: 0, number: 43 },
    { id: "canterana_32", name: "Canterana", position: "Canterana", date_birth: "", birth_place: "", country: "es", height: 0, weight: 0, number: 32 }
]